--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: check_permissions(text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.check_permissions(required_permission text) RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO ''
    AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.user_roles ur
    JOIN public.role_permissions rp ON rp.role_id = ur.role_id
    JOIN public.permissions p ON p.id = rp.permission_id
    WHERE ur.user_id = (select auth.uid())
      AND (p.path = required_permission OR p.path = 'auth:superuser')
  );
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: board_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board_permissions (
    board uuid NOT NULL,
    permission uuid NOT NULL
);


--
-- Name: boards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.boards (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    name character varying NOT NULL,
    "user" uuid,
    workspace uuid NOT NULL,
    is_public boolean DEFAULT true NOT NULL
);


--
-- Name: card_activities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.card_activities (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    activity text NOT NULL,
    "user" uuid,
    card uuid NOT NULL
);


--
-- Name: card_attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.card_attachments (
    card uuid NOT NULL,
    file uuid NOT NULL
);


--
-- Name: cards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cards (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated timestamp with time zone,
    name character varying NOT NULL,
    description text,
    color character varying,
    "position" numeric,
    reminder_date timestamp with time zone,
    due_date timestamp with time zone,
    estimated_time_spent numeric,
    actual_time_spent numeric,
    estimated_time_unit character varying DEFAULT ''::character varying,
    actual_time_unit character varying,
    is_active boolean DEFAULT true NOT NULL,
    list uuid NOT NULL
);


--
-- Name: check_list_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.check_list_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    is_checked boolean DEFAULT false NOT NULL,
    "position" numeric,
    card uuid
);


--
-- Name: comment_attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comment_attachments (
    comment uuid NOT NULL,
    file uuid NOT NULL
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    comment text NOT NULL,
    "user" uuid,
    card uuid NOT NULL
);


--
-- Name: general_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.general_settings (
    id bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    app_name character varying DEFAULT 'Kanban Board'::character varying NOT NULL,
    app_description text,
    show_announcement_banner boolean DEFAULT false NOT NULL,
    announcement_message text,
    announcement_type character varying DEFAULT 'info'::character varying NOT NULL,
    CONSTRAINT general_settings_id_check CHECK ((id = 1))
);


--
-- Name: general_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.general_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.general_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.labels (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    name character varying NOT NULL,
    color character varying,
    board uuid
);


--
-- Name: lists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lists (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    name character varying NOT NULL,
    color character varying,
    "position" numeric NOT NULL,
    board uuid NOT NULL
);


--
-- Name: permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permissions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    path character varying NOT NULL
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    "user" uuid NOT NULL,
    thumbnail uuid,
    username character varying NOT NULL,
    first_name character varying,
    last_name character varying
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permissions (
    role uuid NOT NULL,
    permission uuid NOT NULL
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying NOT NULL
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    "user" uuid NOT NULL,
    role uuid NOT NULL
);


--
-- Name: workspace_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspace_permissions (
    workspace uuid NOT NULL,
    permission uuid NOT NULL
);


--
-- Name: workspaces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspaces (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    name character varying NOT NULL,
    description text,
    is_public boolean DEFAULT false NOT NULL,
    "user" uuid
);


--
-- Name: board_permissions board_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_permissions
    ADD CONSTRAINT board_permissions_pkey PRIMARY KEY (board, permission);


--
-- Name: boards boards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boards
    ADD CONSTRAINT boards_pkey PRIMARY KEY (id);


--
-- Name: card_activities card_activities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_activities
    ADD CONSTRAINT card_activities_pkey PRIMARY KEY (id);


--
-- Name: card_attachments card_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_attachments
    ADD CONSTRAINT card_attachments_pkey PRIMARY KEY (card, file);


--
-- Name: cards cards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_pkey PRIMARY KEY (id);


--
-- Name: check_list_items check_list_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.check_list_items
    ADD CONSTRAINT check_list_items_pkey PRIMARY KEY (id);


--
-- Name: comment_attachments comment_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_attachments
    ADD CONSTRAINT comment_attachments_pkey PRIMARY KEY (comment, file);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: general_settings general_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.general_settings
    ADD CONSTRAINT general_settings_pkey PRIMARY KEY (id);


--
-- Name: labels labels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.labels
    ADD CONSTRAINT labels_pkey PRIMARY KEY (id);


--
-- Name: lists lists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lists
    ADD CONSTRAINT lists_pkey PRIMARY KEY (id);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (role, permission);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY ("user", role);


--
-- Name: workspace_permissions workspace_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_permissions
    ADD CONSTRAINT workspace_permissions_pkey PRIMARY KEY (workspace, permission);


--
-- Name: workspaces workspaces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT workspaces_pkey PRIMARY KEY (id);


--
-- Name: board_permissions board_permissions_board_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_permissions
    ADD CONSTRAINT board_permissions_board_fkey FOREIGN KEY (board) REFERENCES public.boards(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: board_permissions board_permissions_permission_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_permissions
    ADD CONSTRAINT board_permissions_permission_fkey FOREIGN KEY (permission) REFERENCES public.permissions(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: boards boards_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boards
    ADD CONSTRAINT boards_user_fkey FOREIGN KEY ("user") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: boards boards_workspace_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boards
    ADD CONSTRAINT boards_workspace_fkey FOREIGN KEY (workspace) REFERENCES public.workspaces(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: card_activities card_activities_card_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_activities
    ADD CONSTRAINT card_activities_card_fkey FOREIGN KEY (card) REFERENCES public.cards(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: card_activities card_activities_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_activities
    ADD CONSTRAINT card_activities_user_fkey FOREIGN KEY ("user") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: card_attachments card_attachments_card_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_attachments
    ADD CONSTRAINT card_attachments_card_fkey FOREIGN KEY (card) REFERENCES public.cards(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: card_attachments card_attachments_file_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_attachments
    ADD CONSTRAINT card_attachments_file_fkey FOREIGN KEY (file) REFERENCES storage.objects(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: cards cards_list_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_list_fkey FOREIGN KEY (list) REFERENCES public.lists(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: check_list_items check_list_items_card_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.check_list_items
    ADD CONSTRAINT check_list_items_card_fkey FOREIGN KEY (card) REFERENCES public.cards(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: comment_attachments comment_attachments_comment_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_attachments
    ADD CONSTRAINT comment_attachments_comment_fkey FOREIGN KEY (comment) REFERENCES public.comments(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: comment_attachments comment_attachments_file_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_attachments
    ADD CONSTRAINT comment_attachments_file_fkey FOREIGN KEY (file) REFERENCES storage.objects(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: comments comments_card_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_card_fkey FOREIGN KEY (card) REFERENCES public.cards(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: comments comments_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_user_fkey FOREIGN KEY ("user") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: labels labels_board_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.labels
    ADD CONSTRAINT labels_board_fkey FOREIGN KEY (board) REFERENCES public.boards(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: lists lists_board_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lists
    ADD CONSTRAINT lists_board_fkey FOREIGN KEY (board) REFERENCES public.boards(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: profiles profiles_thumbnail_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_thumbnail_fkey FOREIGN KEY (thumbnail) REFERENCES storage.objects(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: profiles profiles_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_user_fkey FOREIGN KEY ("user") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: role_permissions role_permissions_permission_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_permission_fkey FOREIGN KEY (permission) REFERENCES public.permissions(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: role_permissions role_permissions_role_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_role_fkey FOREIGN KEY (role) REFERENCES public.roles(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: user_roles user_roles_role_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_role_fkey FOREIGN KEY (role) REFERENCES public.roles(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: user_roles user_roles_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_user_fkey FOREIGN KEY ("user") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: workspace_permissions workspace_permissions_permission_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_permissions
    ADD CONSTRAINT workspace_permissions_permission_fkey FOREIGN KEY (permission) REFERENCES public.permissions(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: workspace_permissions workspace_permissions_workspace_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_permissions
    ADD CONSTRAINT workspace_permissions_workspace_fkey FOREIGN KEY (workspace) REFERENCES public.workspaces(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: workspaces workspaces_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT workspaces_user_fkey FOREIGN KEY ("user") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: board_permissions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.board_permissions ENABLE ROW LEVEL SECURITY;

--
-- Name: boards board_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY board_read ON public.boards FOR SELECT TO authenticated USING (((( SELECT auth.uid() AS uid) = "user") OR
CASE
    WHEN (is_public = true) THEN public.check_permissions('board:read'::text)
    ELSE (EXISTS ( SELECT 1
       FROM (((public.board_permissions bp
         JOIN public.permissions p ON ((p.id = bp.permission)))
         JOIN public.role_permissions rp ON ((rp.permission = p.id)))
         JOIN public.user_roles ur ON ((ur.role = rp.role)))
      WHERE (bp.board = boards.id)))
END OR public.check_permissions('board:manage'::text)));


--
-- Name: boards; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.boards ENABLE ROW LEVEL SECURITY;

--
-- Name: card_activities; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.card_activities ENABLE ROW LEVEL SECURITY;

--
-- Name: card_attachments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.card_attachments ENABLE ROW LEVEL SECURITY;

--
-- Name: cards; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;

--
-- Name: check_list_items; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.check_list_items ENABLE ROW LEVEL SECURITY;

--
-- Name: comment_attachments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.comment_attachments ENABLE ROW LEVEL SECURITY;

--
-- Name: comments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

--
-- Name: general_settings; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.general_settings ENABLE ROW LEVEL SECURITY;

--
-- Name: labels; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.labels ENABLE ROW LEVEL SECURITY;

--
-- Name: lists; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.lists ENABLE ROW LEVEL SECURITY;

--
-- Name: permissions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;

--
-- Name: profiles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

--
-- Name: role_permissions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;

--
-- Name: roles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;

--
-- Name: user_roles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

--
-- Name: workspaces workspace_create; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY workspace_create ON public.workspaces FOR INSERT TO authenticated WITH CHECK ((public.check_permissions('workspace:create'::text) OR public.check_permissions('workspace:manage'::text)));


--
-- Name: workspaces workspace_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY workspace_delete ON public.workspaces FOR DELETE TO authenticated USING ((((( SELECT auth.uid() AS uid) = "user") AND public.check_permissions('workspace:delete'::text)) OR public.check_permissions('workspace:manage'::text)));


--
-- Name: workspace_permissions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.workspace_permissions ENABLE ROW LEVEL SECURITY;

--
-- Name: workspaces workspace_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY workspace_read ON public.workspaces FOR SELECT TO authenticated USING (((( SELECT auth.uid() AS uid) = "user") OR
CASE
    WHEN (is_public = true) THEN public.check_permissions('workspace:read'::text)
    ELSE (EXISTS ( SELECT 1
       FROM (((public.workspace_permissions wp
         JOIN public.permissions p ON ((p.id = wp.permission)))
         JOIN public.role_permissions rp ON ((rp.permission = p.id)))
         JOIN public.user_roles ur ON ((ur.role = rp.role)))
      WHERE (wp.workspace = workspaces.id)))
END OR public.check_permissions('workspace:manage'::text)));


--
-- Name: workspaces workspace_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY workspace_update ON public.workspaces FOR UPDATE TO authenticated USING ((((( SELECT auth.uid() AS uid) = "user") AND public.check_permissions('workspace:update'::text)) OR public.check_permissions('workspace:manage'::text))) WITH CHECK ((((( SELECT auth.uid() AS uid) = "user") AND public.check_permissions('workspace:update'::text)) OR public.check_permissions('workspace:manage'::text)));


--
-- Name: workspaces; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.workspaces ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

